### ISSUE TITLE
unknown conversion type character 'h' in format

### ISSUE THREAD

**Issue by cieplutki** [orex/cpp_rsc#4]
don't know whether it's typo or something but what you meant by 
`sprintf(buf, "%hhx", c);
`

```
In file included from cpp_rsc.cpp:15:
rsc_create_files.h: In member function 'void rsc_create_files::write_hex_data(std::istream&, std::ostream&, bool, int&)':
rsc_create_files.h:163: warning: unknown conversion type character 'h' in format
rsc_create_files.h:163: warning: too many arguments for format

```

although I thought it would be the reason for the another problem (below) it isn't, i put "%02x" as I thought would be more appropriate but didn't help

there are mistakes in formatting of bytes:
it makes single character "doubled" - no idea how compiler will interpret that and no idea how will anyone manually correct thousands of them in bigger files

```
  const unsigned char clear_gif[] = 
  {
  0x47, 
  0x49, 
  0x46, 
  0x38, 
  0x39, 
  0x61, 
  0x01, 
  0x00, 
  (...)
  0xfff3,  // should be 0xf3
  0x00, 
  0x00, 
  0xffff, // should be 0xff
  0xffff, 
  0x21, 
  0xfff9, // should be 0xf9 
  0x04, 
  (...)
  0x44, 
  0x00, 
  0x3b,  // there shouldn't be this `,' here as it's last line

  }; /* End of clear.gif */
```

it works pretty much as expected, except that manual correction of few mistakes

you should consider aligning 8 or 16 bytes in row not juts one

**Comment by orex** [comment]
Please, provide an information about your compiler, platform, OS etc. It looks like, that it is a compiler specific issue. It looks like, that your compiler is not supported "hh" declaration.
http://www.cplusplus.com/reference/cstdio/printf/

**Comment by orex** [comment]
Please, try a new version.

**Comment by cieplutki** [comment]
Hello,
my compiler is gcc-4.4.0, not brand new, I know but I've just checked gcc-4.9.2 with same result
That wouldn't be an issue - it doesn't matter how you format it and whether compiler like gcc picks it up or not but the code generates wrong output:
I made a binary file with values form 0x00 to 0xFF and ordered your program to make a resource - everything went fine until 0x80
--cut 256.c--
 
#include "256.h"
  /\* Variable __256 from file 256 _/
  const unsigned char __256[] =
  {
  0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
  (...)
  0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0xff80,
  0xff81, 0xff82, 0xff83, 0xff84, 0xff85, 0xff86, 0xff87, 0xff88, 0xff89,
  (...)
  0xfff6, 0xfff7, 0xfff8, 0xfff9, 0xfffa, 0xfffb, 0xfffc, 0xfffd, 0xfffe,
  0xffff
  }; /_ End of 256 _/
-- EOF 256.c
 
--cut 256.h--
#ifndef 256_H
#define 256_H
  /_ Variable __256 from file 256 _/
  extern const unsigned char __256[];
  /_ Variable __256 size. _/
  const int __256_size = 256;
#endif /_256_H */
-- EOF 256.h
 
all values > 0x7F get promoted to short int
it should be 0x80 not 0xff80, isn't it?
 
when I included it in program I go warning for every single wrong character:
256.cpp:37: warning: large integer implicitly truncated to unsigned type
imagine what will happen when resource will be just 10kBi
 
you should explicitly cast on unsigned char parameter passed to sprintf and this will work
 
sprintf(buf, "%hhx", (unsigned char)c);
 
or even better
 
sprintf(buf, "%02x", (unsigned char)c);
 
without any warnings from any compiler
 
$5.00
 
 
thank you

**Comment by cieplutki** [comment]
and you should add some underscore in the .h file
#ifndef 256_H
#define 256_H
#endif /_256_H */
 
because you'll get
256.h:8:9: error: macro names must be identifiers
this will do:
 
#ifndef _256_H
#define _256_H
#endif /__256_H */
 
as 256_H is not proper variable name
 
with file name like '256' (or anything starting with digit) it will happen
 
another $5.00
 
thank you

**Comment by orex** [comment]
It is not so easy to win even $10 as you think. First of all, CHECK A NEW VERSION! It is free of C obsolete functions. 

> sprintf(buf, "%02x", (unsigned char)c);
> 
> without  any warnings from any compiler

Any compiler you means, gcc and gcc and, probably, gcc? Clang, for example, gives the warning. I solve this problem before. Moreover, this construct is potentially dangerous. For files, starting with numeric, you are right. I will change the code.

**Comment by orex** [comment]
Header protection fixed.
