### ISSUE TITLE
The concept

### ISSUE THREAD

**Issue by kornerr** [orex/cpp_rsc#5]
Hi.
I've found your library when was looking for an embedded file system solution.
However, fast code scan didn't reveal the concept to me.

Can you please describe briefly how you process binary data, store it, and then read it back from an executable?
Thanks.

**Comment by orex** [comment]
Hi!

Have you seen this post in stackoverflow: [cpp_rsc](https://stackoverflow.com/a/19180226) Something from your request is described there. Also you can clone the program and check the example.

The program consist of two parts: 
1) A program, which creates a C/C++ files (header+source) with static variables of binary data from resource files. So, compare to the other solutions, it is working on compile, but not linking stage. Therefore it is better compatible with different compilers, platforms, compiler options etc.
2) CMake files, which integrates the program to CMake scripts.

About your question:
1)  "process binary data" - read input file binary and store it in C/C++ source file as binary byte array. The data can have hex or char representation.
2)  "store it" - the data stores like a static variable. The details depends on platform, compiler etc.
3) To read it back, you just need to loop through the array. For C++ you can use it like a stream also. You will need a special rdbuf for this. If you set text flag, for resource compiling, you can use the variable like a C style sting (null terminated array of char).

This is a brief description. Feel free to ask any details.
